# -*- coding: utf-8 -*-
"""app3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGMGiBTVBwroK-0UsS1euG7X0i8iX_b7
"""

import streamlit as st
from insurance_blockchain import InsuranceBlockchain

st.set_page_config(page_title="InsurTech Demo", page_icon="🛡️")

# Initialize blockchain in the session
if 'blockchain' not in st.session_state:
    st.session_state.blockchain = InsuranceBlockchain()

st.title("🛡️ Financial Insurance Blockchain")
st.markdown("---")

sidebar = st.sidebar.radio("Navigate", ["Issue Policy", "Blockchain Ledger", "System Integrity"])

if sidebar == "Issue Policy":
    st.header("Create New Insurance Contract")
    with st.form("policy_form"):
        client = st.text_input("Client Name")
        coverage = st.selectbox("Coverage", ["Asset Protection", "Default Swap", "Yield Guarantee"])
        value = st.number_input("Premium Amount", min_value=0.0)
        submitted = st.form_submit_button("Seal Block")

        if submitted:
            # Add transaction
            st.session_state.blockchain.add_transaction(
                sender="Bank_Auth",
                receiver=client,
                amount=value,
                policy_details={"type": coverage, "status": "Active"}
            )
            # Mine block
            prev_hash = st.session_state.blockchain.hash(st.session_state.blockchain.get_last_block())
            st.session_state.blockchain.create_block(proof=101, previous_hash=prev_hash)
            st.success(f"Policy for {client} verified and added to the chain!")

elif sidebar == "Blockchain Ledger":
    st.header("Public Immutable Ledger")
    for block in reversed(st.session_state.blockchain.chain):
        with st.expander(f"Block #{block['index']} | Hash: {st.session_state.blockchain.hash(block)[:20]}..."):
            st.write(f"**Timestamp:** {block['timestamp']}")
            st.write(f"**Previous Hash:** {block['previous_hash']}")
            st.write("**Transactions:**")
            st.table(block['transactions'])

elif sidebar == "System Integrity":
    st.header("Security Audit")
    is_valid = st.session_state.blockchain.is_chain_valid()
    if is_valid:
        st.success("Blockchain Integrity Verified: All hashes match.")
    else:
        st.error("ALERT: Blockchain Integrity Compromised! Hash mismatch detected.")